# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tmdb 0.7.0 ruby lib

Gem::Specification.new do |s|
  s.name = "tmdb"
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Cody Barr"]
  s.date = "2014-08-05"
  s.description = "tmdb is a simple ruby wrapper for The Movie Database.  Exposes all TMDB API operations"
  s.email = "cody.barr@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/tmdb.rb",
    "lib/tmdb/api.rb",
    "lib/tmdb/movie.rb",
    "lib/tmdb/tv.rb",
    "test/test_helper.rb",
    "test/tmdb/test_api.rb",
    "test/tmdb/test_movie.rb",
    "test/tmdb/test_tv.rb",
    "tmdb.gemspec"
  ]
  s.homepage = "http://github.com/codybarr/tmdb"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.1"
  s.summary = "A simple ruby wrapper for _The MovieDB API_ based on HTTParty"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.13.1", "~> 0.13"])
      s.add_runtime_dependency(%q<hashie>, [">= 2.1.1", "~> 2.1"])
      s.add_development_dependency(%q<shoulda>, [">= 3.5.0", "~> 3.5"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0.8.2", "~> 0.8"])
      s.add_development_dependency(%q<rake-notes>, [">= 0.2.0", "~> 0.2"])
    else
      s.add_dependency(%q<httparty>, [">= 0.13.1", "~> 0.13"])
      s.add_dependency(%q<hashie>, [">= 2.1.1", "~> 2.1"])
      s.add_dependency(%q<shoulda>, [">= 3.5.0", "~> 3.5"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
      s.add_dependency(%q<simplecov>, [">= 0.8.2", "~> 0.8"])
      s.add_dependency(%q<rake-notes>, [">= 0.2.0", "~> 0.2"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.13.1", "~> 0.13"])
    s.add_dependency(%q<hashie>, [">= 2.1.1", "~> 2.1"])
    s.add_dependency(%q<shoulda>, [">= 3.5.0", "~> 3.5"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    s.add_dependency(%q<simplecov>, [">= 0.8.2", "~> 0.8"])
    s.add_dependency(%q<rake-notes>, [">= 0.2.0", "~> 0.2"])
  end
end

